const fixDuplicates = require('../src/fix-duplicates');
const lockfile = require('@yarnpkg/lockfile');

test('dedupes lockfile to max compatible version', () => {
    const packageJsonData = `
  {
      "dependencies": {
          "foo": ">=1.0.0",
          "lodash": ">=1.0.0"
      }
  }
`;
    const lockfileData = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

foo@>=1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#deadbeef"
  dependencies:
    lodash ">=2.0.0"

lodash@>=1.0.0:
  version "1.3.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-1.3.1.tgz#a4663b53686b895ff074e2ba504dfb76a8e2b770"

lodash@>=2.0.0:
  version "4.17.4"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.4.tgz#78203a4d1c328ae1d86dca6460e369b57f4055ae"
`;

    const deduped = fixDuplicates(packageJsonData, lockfileData);
    const json = lockfile.parse(deduped).object;

    expect(json['lodash@>=1.0.0'].version).toEqual('4.17.4');
    expect(json['lodash@>=2.0.0'].version).toEqual('4.17.4');
});

test('downgrades if lower compatible version is pinned', () => {
    const packageJsonData = `
  {
      "dependencies": {
          "foo": ">=2.0.0",
          "lodash": "^3.0.0"
      }
  }
`;
    const lockfileData = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

foo@>=2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-2.0.0.tgz#deadbeef"
  dependencies:
    lodash ">=1.0.0"

lodash@>=1.0.0:
  version "4.17.4"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.4.tgz#78203a4d1c328ae1d86dca6460e369b57f4055ae"

lodash@^3.0.0:
  version "3.10.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz#5bf45e8e49ba4189e17d482789dfd15bd140b7b6"
`;

    const deduped = fixDuplicates(packageJsonData, lockfileData);
    const json = lockfile.parse(deduped).object;

    expect(json['lodash@>=1.0.0'].version).toEqual('3.10.1');
    expect(json['lodash@^3.0.0'].version).toEqual('3.10.1');
});

test('removes extraneous dependencies after deduping', () => {
    const packageJsonData = `
  {
      "dependencies": {
          "foo": ">=2.0.0",
          "bar": ">=3.0.0"
      }
  }
`;
    const lockfileData = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

foo@>=2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-2.0.0.tgz#deadbeef"
  dependencies:
    bar ">=1.0.0"

bar@>=3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/bar/-/bar-3.0.1.tgz#deadbeef"

bar@>=1.0.0:
  version "2.5.0"
  resolved "https://registry.yarnpkg.com/bar/-/bar-2.5.0.tgz#deadbeef"
  dependencies:
    baz ">=1.0.0"

baz@>=1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/baz/-/baz-1.0.0.tgz#deadbeef"
`;

    const deduped = fixDuplicates(packageJsonData, lockfileData);
    const json = lockfile.parse(deduped).object;

    expect(json['bar@>=3.0.0'].version).toEqual('3.0.1');
    expect(json['bar@>=1.0.0'].version).toEqual('3.0.1');
    expect(json['baz@>=1.0.0']).toBeUndefined();
});
